language: node_js
node_js:
- 4.0.0
install:
- npm install
script: npm test
deploy:
  provider: openshift
  user: $EMAIL_ADDRESS
  password:
    secure: FgNtNFw/koZXBbeB9OhjGBGEUJ6nyPZL5u6rOgqHzUZDcbK5T3P5nkqCT2uZ+0semhxrkl+MqpjCAwECge+vKRvgC0sMMzQzPOZueY7GTIn0ceeH3AXAhez/SX6K1c/GEswdTc2hQ8DEjovyiZPjvEp65KKp9jjQuf+eBj3iHaMS1866zSVh6h0101tLSymAiLaG4nlVFcLTPXRrX3ZmdAM2G/8FltH+NcvnI4A4oelEFBmKb2MRe7LDpHDBoJybJewmcYIJ73kjhFr0TQ897ezGUHrp/Jf06gT9euWpXlWDSGSz8iRTHtqTa4RVLJEalF9G9OxYGYg54O2oTSipmPcmCc1Cy80oNNO4OAUEB407LziFox8Pt5ouJrQyZCwniRHZYNIXyvrh9pTxIz6dYapUUP1Gb5M5Ns24KMFgNDj94mbdhPWNbws3wvYlqTqueplQ5gB5e0SBEeWXlM28r7deN7aJ+TJrA/flc+EKy9of7hKNsTlCP5t+aiWUa65afvEtni+dizVAqq6VK1nHf1HzHF8eW+8PbrToBREdGHhgPZcDtWzKQAUdDHv2EDYmYXgaJErK0IFlWMfX4Zx1CgTvz/tgaLZ6V7zfUHUTwUAksLXxpNUow2Ok3ckYhvK8v5Gq0gJAMf+Lwj+oGiDmK/eBP6KM2MxGKnwtX60CaZI=
  app: node-drazious
  domain: node-drazious.rhcloud.com
  on:
    repo: amrdraz/openshift-travis-wercker
