language: node_js
node_js:
  - 4.0.0
install:
  - npm install
script: npm test

deploy:
  provider: openshift
  user: $EMAIL_ADDRESS
  password: $PASSWORD
  app: $APP_NAME
  domain: $DOMAIN_NAME
  on: master
